Repository astronomer/houston-api, pull requests merged in 2020-03, with the labels that each got.

#240 Allow system roles to supersede workspace roles
  src/schema.graphql
Labels: kind/bug

#251 Mailer template cleanup
  src/lib/emails/templates/alert/html.hbs
  src/lib/emails/templates/confirm-email/html.hbs
  src/lib/emails/templates/forgot-password/html.hbs
  src/lib/emails/templates/layouts/main.hbs
  src/lib/emails/templates/user-invite/html.hbs
Labels: kind/cleanup

#253 Allow access to alertmanager and prometheus via the system.monitoring.get permission
  src/routes/v1/authorization/handler.js
Labels: kind/feature
