Repository astronomer/houston-api, pull requests merged in 2020-05, with the labels that each got.

#297 Update file name
  src/resolvers/mutation/add-customer-id/index.unit.test.js
Labels: area/houston-api

#295 Add more tests for deployment/logs
  codecov.yml
  src/lib/deployments/logs/index.js
  src/lib/deployments/logs/index.unit.test.js
Labels: 0.15, area/houston-api

#305 Add coverage threshold for jest
  codecov.yml
  jest.config.js
Labels: 0.16, area/houston-api

#296 Issue#1339 test coverage validate
  src/lib/deployments/validate/properties/index.js
  src/lib/deployments/validate/properties/index.unit.test.js
Labels: 0.16, area/houston-api
