Repository astronomer/houston-api, pull requests merged in 2020-06, with the labels that each got.

#301 Adding unit test cases for invites
  .gitignore
  package-lock.json
  src/resolvers/types/invite/index.unit.test.js
  src/routes/v1/registry/events/index.unit.test.js
  src/schema/query.js
Labels: 0.16

#311 Fix: deployment name validation
  src/lib/deployments/validate/authorization/index.js
  src/lib/deployments/validate/authorization/index.unit.test.js
Labels: 0.15

#272 Env variable schema
  src/resolvers/mutation/index.js
  src/resolvers/mutation/update-deployment-variables/fragments.js
  src/resolvers/mutation/update-deployment-variables/index.js
  src/resolvers/mutation/update-deployment-variables/index.unit.test.js
  src/resolvers/query/deployment-variables/index.js
  src/resolvers/query/deployment-variables/index.unit.test.js
  src/resolvers/query/index.js
  src/schema.graphql
Labels: 0.16

#335 fix registry repo validation to new reg expression
  src/lib/constants/index.js
  src/lib/deployments/naming/index.js
  src/lib/deployments/naming/index.unit.test.js
  src/lib/deployments/validate/authorization/index.js
  src/lib/deployments/validate/docker-tag/index.js
  src/routes/v1/authorization/handler.js
  src/routes/v1/registry/authorization/handler.js
Labels: 0.15, kind/bug

#339 Add deployments validate tests
  src/lib/deployments/validate/index.unit.test.js
Labels: area/houston-api

#336 Increasing code coverage for query logs
  src/resolvers/query/logs/index.unit.test.js
Labels: area/houston-api

#346 Mutation fix + schema cleanup
  src/lib/deployments/environment-variables/index.js
  src/lib/deployments/validate/environment/index.unit.test.js
  src/lib/deployments/validate/index.js
  src/resolvers/mutation/create-deployment/index.js
  src/resolvers/mutation/create-deployment/index.unit.test.js
  src/resolvers/mutation/update-deployment-variables/index.js
  src/resolvers/mutation/update-deployment-variables/index.unit.test.js
  src/resolvers/mutation/update-deployment/index.js
  src/resolvers/mutation/update-deployment/index.unit.test.js
  src/resolvers/mutation/upgrade-deployment/index.unit.test.js
  src/resolvers/query/deployment-variables/index.js
  src/resolvers/query/deployment-variables/index.unit.test.js
  src/resolvers/query/deployments/index.unit.test.js
  src/resolvers/query/workspace-deployment/index.unit.test.js
  src/resolvers/query/workspace-deployments/index.unit.test.js
  src/resolvers/types/deployment/index.js
  src/resolvers/types/deployment/index.unit.test.js
  src/schema.graphql
Labels: kind/bug, kind/cleanup

#351 Fix environment variable key validation
  src/lib/deployments/environment-variables/validate/index.js
  src/lib/deployments/environment-variables/validate/index.unit.test.js
  src/lib/deployments/validate/index.js
  src/resolvers/mutation/update-deployment-variables/index.js
Labels: kind/bug

#350 Upgrading open id client package
  config/test.yaml
  package.json
  src/lib/oauth/config/index.js
  src/lib/oauth/config/index.unit.test.js
  src/resolvers/types/auth-config/index.js
  src/resolvers/types/auth-config/index.unit.test.js
  src/routes/v1/oauth/callback/index.unit.test.js
  src/routes/v1/oauth/callback/post.js
  yarn.lock
Labels: area/houston-api
